ShiviBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from .views import *

app_name = 'article'
urlpatterns = [
    path('', index, name = 'index'),
    path('article/<int:pk>/', single_article, name = 'single_article')
]

article/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 50)

    class Meta:
        verbose_name = 'Categories'
    
    def __str__(self):
        return self.name


class Article(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE, default = 1)  
    title = models.CharField(max_length=50)
    content = models.TextField(max_length = 2000)
    img = models.ImageField(upload_to='article_images/', default= 'default_img.jpg')
    pub_date = models.DateField(auto_now= True)

    def __str__(self):
        return self.title

article/views.py
from django.shortcuts import render
from .models import *

# Create your views here.

def categories(request):          
    categories = Category.objects.all()

    return{
        'categories': categories,
    }


def index(request):
    all_articles = Article.objects.all()

    context = {
        'articles': all_articles
    }
    return render(request, 'article/index.html', context)

def single_article(request):
    article = Article.objects.get(pk=pk)

    context = {
        "article": article,
    }
    return render(request, 'article/article.html', context)

article/templates/article/article.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2 class="mt-4" style="width:80%;">{{article.title}}</h2>
    <h5 class="m-2">Published on {{article.pub_date}}</h5>
    <img class="my-3" style="width: 80%;"  src="{{article.img.url}}" alt="">
    <p style="width: 80%;">{{article.content}}</p>
</div>

{% endblock content %}

article/templates/article/index.html
{% extends "base.html" %}

{% block content %}

<h1>This is index.html</h1>

<div class="container ">
    <h2>All Articles</h2>
    <div class="row g-lg-2">
        {% for article in articles %}
        <div class='col-md-4 col-lg-3 col-sm-6'>  
            <div class="card m-4" style="width: 18rem;"> 
                <img style="height:230px;" src="{{article.img.url}}" class="card-img-top img-fluid" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{article.title | truncatewords:5}}</h5>
                    <p class="card-text">{{article.content | truncatewords:20 }}</p>
                    <a href="{% url "article:single_article"  article.id%}" class="text-decoration-none">read more</a>
                </div> 
            </div> 
        </div>  
        {% endfor %} 
    </div> 
</div> 
 

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    {% block nav %}

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url "article:index" %}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url "article:index" %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
                </a>
                <ul class="dropdown-menu">

                  {% for category in categories %}
                  
                  <li><a class="dropdown-item" href="#">{{category}}</a></li>
                  
                  {% endfor %}


                  <li><a class="dropdown-item" href="#">All</a></li>
                  <li><hr class="dropdown-divider"></li>
                </ul>
              </li>
              <li class="nav-item">
                
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

    {% endblock nav %}


    {% block content %}
    
    {% endblock content %}


    {% block footer %}
    
    {% endblock footer %}
</body>
</html>